global:
  scrape_interval: 15s # Domyślny interwał dla wszystkich zadań
  evaluation_interval: 15s # Jak często obliczać reguły alertów

scrape_configs:
  # Twój główny cel - aplikacja Flask
  - job_name: "flask-app"
    scrape_interval: 15s
    metrics_path: "/prometheus"
    static_configs:
      - targets: ["flask_app:5000"]

  # Monitoring samego Prometheusa (Best Practice)
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
